# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('profile_picture', models.ImageField(upload_to='images/', verbose_name='profile_picture')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('ssn_id', models.CharField(max_length=500, verbose_name='ssn_id')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='gender')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
            ],
            options={
                'verbose_name': 'AdsManager',
                'verbose_name_plural': 'AdsManagers',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiserName', models.CharField(max_length=500, verbose_name='advertiser_name')),
                ('advertiserEmail', models.EmailField(max_length=254, verbose_name='advertiser_email')),
                ('advertiserPhone', models.CharField(max_length=500, verbose_name='advertiser_phone')),
                ('image', models.FileField(upload_to='images/', verbose_name='image')),
                ('page', models.CharField(max_length=500, verbose_name='page')),
                ('startDate', models.DateField(verbose_name='start_date')),
                ('endDate', models.DateField(verbose_name='end_date')),
                ('show_num', models.PositiveIntegerField(verbose_name='show_num')),
                ('duration', models.PositiveIntegerField(blank=True, choices=[(15, '15s'), (30, '30s'), (45, '45s'), (60, '60s'), (75, '75s'), (90, '90s'), (105, '105s'), (120, '120s')], null=True, verbose_name='duration')),
                ('interval', models.PositiveIntegerField(blank=True, choices=[(5, '5m'), (10, '10m')], null=True, verbose_name='interval')),
                ('nextShowTime', models.DateField(blank=True, null=True, verbose_name='next_show-time')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False)),
                ('advertiseManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.AdsManager', verbose_name='advertise_manager')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
