# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('profile_picture', models.ImageField(upload_to='images/', verbose_name='profile_picture')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('ssn_id', models.CharField(max_length=500, verbose_name='ssnid')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='gender')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
            ],
            options={
                'verbose_name': 'Delegate',
                'verbose_name_plural': 'Delegates',
            },
        ),
    ]
