# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='user')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('message', models.CharField(max_length=20000, verbose_name='message')),
                ('document1', models.FileField(blank=True, null=True, upload_to='emails/', verbose_name='document1')),
                ('document2', models.FileField(blank=True, null=True, upload_to='emails/', verbose_name='document2')),
                ('document3', models.FileField(blank=True, null=True, upload_to='emails/', verbose_name='document3')),
                ('document4', models.FileField(blank=True, null=True, upload_to='emails/', verbose_name='document4')),
                ('document5', models.FileField(blank=True, null=True, upload_to='emails/', verbose_name='document5')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mails',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='music')),
                ('music', models.FileField(blank=True, null=True, upload_to='music/', verbose_name='music')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name_ar')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('address_ar', models.CharField(max_length=200, verbose_name='address_ar')),
                ('postal_code', models.CharField(max_length=100, verbose_name='postal_code')),
                ('logo', models.ImageField(upload_to='site/', verbose_name='logo')),
                ('logo_2', models.ImageField(upload_to='site/', verbose_name='logo_2')),
                ('login_logo', models.ImageField(upload_to='site/', verbose_name='login_logo')),
                ('facebook', models.URLField(max_length=500, verbose_name='facebook')),
                ('twitter', models.URLField(max_length=500, verbose_name='twitter')),
                ('google', models.URLField(max_length=500, verbose_name='google')),
                ('youtube', models.URLField(max_length=500, verbose_name='youtube')),
                ('wuzzuf', models.URLField(max_length=500, verbose_name='wuzzuf')),
                ('linkedin', models.URLField(max_length=500, verbose_name='linkedin')),
                ('instagram', models.URLField(max_length=500, verbose_name='instagram')),
                ('knicks_link', models.URLField(max_length=500, verbose_name='knicks_link')),
                ('knicks_logo', models.ImageField(upload_to='site/', verbose_name='knicks_logo')),
                ('dollar_rate', models.FloatField(verbose_name='dollar_rate')),
                ('language', models.CharField(choices=[('english', 'english'), ('arabic', 'arabic')], default='english', max_length=100, verbose_name='language')),
            ],
            options={
                'verbose_name': 'SiteInfo',
                'verbose_name_plural': 'SiteInfo',
            },
        ),
    ]
