# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirFreight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_min', models.FloatField(verbose_name='slice_min')),
                ('slice_max', models.FloatField(verbose_name='slice_max')),
                ('rate', models.FloatField(verbose_name='rate')),
                ('initial_cost', models.FloatField(verbose_name='initial_cost')),
                ('price_average', models.FloatField(verbose_name='price_average')),
                ('transport_time', models.FloatField(verbose_name='transport_time')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Air Freight',
                'verbose_name_plural': 'Air Freights',
            },
        ),
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_min', models.FloatField(verbose_name='slice_min')),
                ('slice_max', models.FloatField(verbose_name='slice_max')),
                ('rate', models.FloatField(verbose_name='rate')),
                ('initial_cost', models.FloatField(verbose_name='initial_cost')),
                ('price_average', models.FloatField(max_length=4, verbose_name='price_average')),
                ('transport_time', models.FloatField(verbose_name='transport_time')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Express',
                'verbose_name_plural': 'Express',
            },
        ),
        migrations.CreateModel(
            name='SeaFreight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_min', models.FloatField(verbose_name='slice_min')),
                ('slice_max', models.FloatField(verbose_name='slice_max')),
                ('rate', models.FloatField(verbose_name='rate')),
                ('initial_cost', models.FloatField(verbose_name='initial_cost')),
                ('price_average', models.FloatField(verbose_name='price_average')),
                ('transport_time', models.FloatField(verbose_name='transport_time')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Sea Freight',
                'verbose_name_plural': 'Sea Freights',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('website', models.URLField(max_length=1000, verbose_name='website')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shippings',
            },
        ),
        migrations.CreateModel(
            name='ShippingCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name_ar')),
                ('price', models.FloatField(verbose_name='price')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Shipping Condition',
                'verbose_name_plural': 'Shipping Conditions',
            },
        ),
        migrations.CreateModel(
            name='ShippingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(choices=[('express', 'express'), ('air freight', 'air freight'), ('sea freight', 'sea freight')], default='express', max_length=100)),
                ('days', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Shipping Time',
                'verbose_name_plural': 'Shipping Times',
            },
        ),
    ]
