# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shippings', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingtime',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='shippingtime',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='shippingtime',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippings.Shipping'),
        ),
        migrations.AddField(
            model_name='shippingcondition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='seafreight',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='seafreight',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='seafreight',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippings.Shipping', verbose_name='shipping_company'),
        ),
        migrations.AddField(
            model_name='seafreight',
            name='shipping_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shippings.ShippingCondition', verbose_name='shipping_condition'),
        ),
        migrations.AddField(
            model_name='express',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='express',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='express',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippings.Shipping', verbose_name='shipping_company'),
        ),
        migrations.AddField(
            model_name='express',
            name='shipping_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shippings.ShippingCondition', verbose_name='shipping_condition'),
        ),
        migrations.AddField(
            model_name='airfreight',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='airfreight',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='airfreight',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippings.Shipping', verbose_name='shipping_company'),
        ),
        migrations.AddField(
            model_name='airfreight',
            name='shipping_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shippings.ShippingCondition', verbose_name='shipping_condition'),
        ),
    ]
