# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='add_date')),
                ('specs', models.TextField(blank=True, null=True, verbose_name='specs')),
                ('max_quantity', models.PositiveIntegerField(verbose_name='max_quantity')),
                ('is_trashed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('money_type', models.PositiveSmallIntegerField(choices=[(1, '$ US dollar'), (2, 'EG pound')], default=1, verbose_name='money_type')),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('processing', 'processing'), ('prepared', 'prepared'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('shipped', 'shipped'), ('delivered', 'delivered')], max_length=200, verbose_name='status')),
                ('delegate_report', models.TextField(blank=True, null=True, verbose_name='delegate_report')),
                ('shipping_report', models.TextField(blank=True, null=True, verbose_name='shipping_report')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='specification')),
                ('invoice_id', models.CharField(max_length=200, verbose_name='invoice')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='is_reviewed')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
