# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20200503_1602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shippings', '0001_initial'),
        ('products', '0001_initial'),
        ('user', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified_by'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.Provider', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shippings.Shipping', verbose_name='shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory', verbose_name='sub_category'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BuyerUserDetails', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='history',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
