# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name_ar')),
                ('show_num', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name_ar')),
                ('price', models.FloatField(verbose_name='price')),
                ('provider_price', models.FloatField(verbose_name='provider_price')),
                ('brand_name', models.CharField(max_length=500, verbose_name='brand_name')),
                ('brand_name_ar', models.CharField(max_length=200, verbose_name='brand_name_ar')),
                ('model_number', models.CharField(max_length=500, verbose_name='model_number')),
                ('short_description', models.CharField(max_length=500, verbose_name='short_description')),
                ('short_description_ar', models.CharField(max_length=500, verbose_name='short_description_ar')),
                ('main_img', models.ImageField(upload_to='images/', verbose_name='main_img')),
                ('stars', models.FloatField(verbose_name='stars')),
                ('long_desc_img', models.ImageField(upload_to='images/', verbose_name='long_desc_img')),
                ('process_time', models.FloatField()),
                ('max_quantity', models.IntegerField()),
                ('delay_count', models.IntegerField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('additional_shipping_cost', models.FloatField(verbose_name='additional_shipping_cost')),
                ('show_num', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImages',
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('discount', models.FloatField(verbose_name='discount')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'best'), (2, 'highValue')], null=True, verbose_name='type')),
                ('showed_in', models.PositiveIntegerField(blank=True, choices=[(2, 'slider'), (1, 'adbanner')], null=True, verbose_name='showed_in')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'ProductOffer',
                'verbose_name_plural': 'ProductOffers',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=500, null=True, verbose_name='review')),
                ('stars', models.FloatField(verbose_name='stars')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='ShowRecent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'ShowRecent',
                'verbose_name_plural': 'ShowRecents',
            },
        ),
        migrations.CreateModel(
            name='SpecName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=100, verbose_name='spec_name')),
                ('spec_name_ar', models.CharField(max_length=100, verbose_name='spec_name_ar')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'SpecName',
                'verbose_name_plural': 'SpecNames',
            },
        ),
        migrations.CreateModel(
            name='SpecNameChangeable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=100, verbose_name='spec_name')),
                ('spec_name_ar', models.CharField(max_length=100, verbose_name='spec_name_ar')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'SpecNameChangeable',
                'verbose_name_plural': 'SpecNameChangeables',
            },
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_value', models.CharField(max_length=200, verbose_name='spec_value')),
                ('spec_value_ar', models.CharField(max_length=200, verbose_name='spec_value_ar')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'SpecValue',
                'verbose_name_plural': 'SpecValues',
            },
        ),
        migrations.CreateModel(
            name='SpecValueChangeable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_value', models.CharField(max_length=200, verbose_name='spec_value')),
                ('spec_value_ar', models.CharField(max_length=200, verbose_name='spec_value_ar')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
            ],
            options={
                'verbose_name': 'SpecValueChangeable',
                'verbose_name_plural': 'SpecValueChangeables',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name_ar')),
                ('show_num', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified_on')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
    ]
