# Generated by Django 2.2.9 on 2020-05-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shippings', '0001_initial'),
        ('products', '0001_initial'),
        ('providers', '0001_initial'),
        ('delegates', '0002_delegate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delegates.Delegate', verbose_name='delegate'),
        ),
        migrations.AddField(
            model_name='specvaluechangeable',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='specvaluechangeable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='specvaluechangeable',
            name='spec_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SpecNameChangeable', verbose_name='spec_name'),
        ),
        migrations.AddField(
            model_name='specvalue',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='specvalue',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='specvalue',
            name='spec_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, to='products.SpecName', verbose_name='spec_name'),
        ),
        migrations.AddField(
            model_name='specvalue',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory', verbose_name='sub_category'),
        ),
        migrations.AddField(
            model_name='specnamechangeable',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='specname',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='specname',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory', verbose_name='sub_category'),
        ),
        migrations.AddField(
            model_name='showrecent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='showrecent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory', verbose_name='sub_category'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shippings.ShippingCondition', verbose_name='shipping_condition'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory', verbose_name='sub_category'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
    ]
